Fix java.lang.NoClassDefFoundError: org/apache/oro/text/perl/Perl5Util caused by absence of ORO
Not totally sure why this just became a problem. ORO was embeded in Commons Validator 1.3.0, but is not in 1.3.1, but we switched to 1.3.1 in Roller 5.0.1. I suspect that the recent Lucene changes caused ORO to no longer be a dependency.

git-svn-id: https://svn.apache.org/repos/asf/roller/trunk@1486364 13f79535-47bb-0310-9956-ffa450edef68